### ISSUE TITLE
DbActor Class Error

### ISSUE THREAD

**Issue by singhrahulnet** [AJEETX/ko.signalr.selfhost.akka#1]
@AJEETX 

I had to comment these out - 
`this.Recover<Msg>(RecoverAndHandle, null)`
`this.Command<Msg>(PersistAndHandle, null)`

Error - 

> 
Severity	Code	Description	Project	File	Line
Error	CS0121	The call is ambiguous between the following methods or properties: 'ReceivePersistentActor.Recover<T>(Action<T>, Predicate<T>)' and 'ReceivePersistentActor.Recover<T>(Predicate<T>, Action<T>)'	Akka.DB.Actor	F:\Data\Pers\GIT\ko.signalr.selfhost.akka\Akka.DB\Actor\UserDataActor.cs	37

>

**Comment by AJEETX** [comment]
Please provide details to reproduce the issue.

**Comment by singhrahulnet** [comment]
Compile time error in Akka.DB.Actor project.

![image](https://user-images.githubusercontent.com/18165285/31598236-1c8b2848-b26a-11e7-86e3-7bb31190b4e6.png)

**Comment by AJEETX** [comment]
As I can see in the image, it seems runtime error,please confirm if it is a compile time or runtime error.
 I just downloaded a new copy of code from this repository, restored nugets and then I could build it.

**Comment by AJEETX** [comment]
Closed
